### ISSUE TITLE
Compatibility with LimeSurver 2.67

### ISSUE THREAD

**Issue by Nalmar-x** [SamMousa/limesurvey-encrypt#3]
Are there plans to make this plugin compatible with newer versions on limesurvey ?

**Comment by SamMousa** [comment]
No. This plugin was created for a customer who was fine with it being open sourced.
There's no development planned.

Feel free to make a PR, I'll review and merge it.

**Comment by nalmar** [comment]
Would it be a big job to update it ? How much would you ask to do it (if interested) ?

**Comment by SamMousa** [comment]
I think it won't be much work. Contact me at sam@befound.nl for details.

**Comment by ayian2004** [comment]
Dear @SamMousa and @nalmar did you actually make it work for LimeSurver 2.67?
I am currently using 2.67, I successfully installed it but the decrypt script isn't working!!! The data.csv is empty

**Comment by Nalmar-x** [comment]
No, sorry. I ended up going a different route.
